- name: Настройки отображения
  hosts: all
  #'none' 'wallpaper' 'centered' 'scaled' 'stretched' 'zoom' 'spanned'
  vars:
    option: 
  tasks:
    - name: Проверка установлен ли GNOME
      command: gnome-shell --version
      register: gnome_check
      ignore_errors: true

    - name: Установка GNOME, если не установлен
      dnf:
        name: gnome-desktop
        state: present
      when: gnome_check.rc != 0

    - name:  Проверка установлен ли dconf
      command: dconf-editor --version
      register: dconf_check
      ignore_errors: true

    - name: Установка dconf
      dnf:
        name: dconf-editor
        state: present
      when: dconf_check.rc != 0  

    - name: Изменение фона
      command: dconf write /org/gnome/desktop/background/picture-options "'{{ option }}'"

    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0

