- name: Изменение цвета фона
  hosts: all
  remote_user: root
  become: yes
#цвет в шестнатеричном формате
  vars:
    colorHEX: '#023c88'

  tasks:
    - name: Проверка установлен ли GNOME
      command: gnome-shell --version
      register: gnome_check
      ignore_errors: yes

    - name: Установка GNOME, если не установлен
      dnf:
        name: gnome-desktop
        state: present
      when: gnome_check.rc != 0

    - name:  Проверка установлен ли dconf
      command: dconf-editor --version
      register: dconf_check
      ignore_errors: yes

    - name: Установка dconf
      dnf:
        name: dconf-editor
        state: present
      when: dconf_check.rc != 0   

    - name: Изменение фона
      dconf: 
        key: "/org/gnome/desktop/background/color"
        value: "'{{ colorHEX }}'"

    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0
