- name: Установка шрифта по умолчанию
  hosts: all
  remote_user: root
  become: yes
  vars:
    font_name_and_size: 'Cantarell 14' 

  tasks:
    - include_tasks: checkgnomeinstalled.yaml  

    - name: Изменение шрифта
      dconf:
        key: "/org/gnome/desktop/interface/font-name"
        value: "'{{ font_name_and_size }}'"
      
    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0
