- name: Установка шрифта по умолчанию
  hosts: all
  remote_user: root
  become: yes
  vars:
    font_name: 'Cantarell'
    font_size: '11'

  tasks:
    - include_tasks: checkgnomeinstalled.yaml  

    - name: Изменение шрифта
      command: gsettings set org.gnome.desktop.interface font-name '{{ font_name, font_size }}'

    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0
