- name: Установка и изменение темы GNOME
  hosts: all
  remote_user: root
  become: yes
  vars:
    theme_name: 'Adwaita'

  tasks:
    - include_tasks: checkgnomeinstalled.yaml  

    - name: Установка темы GNOME
      dnf:
        name: gnome-themes-standard
        state: present

    - name: Изменение темы GNOME
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'{{ theme_name }}'"
        state: present

    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0
