- name: Изменение размера текста
  hosts: all
  remote_user: root
  become: yes
  vars:
    factor: '1.5'

  tasks:
    - include_tasks: checkgnomeinstalled.yaml  

    - name: Изменение темы иконок GNOME
      command: gsettings set org.gnome.desktop.interface text-scaling-factor '{{ factor }}'

    - name: Перезапуск GNOME без перезагрузки
      command: killall -3 gnome-shell  
      async: 10
      poll: 0
